### ISSUE TITLE
Links to self (own domain) are blocked

### ISSUE THREAD

**Issue by RubenFixit** [PrivateBin/docker-nginx-fpm-alpine#109]
## Steps to reproduce
1. Include a link to your PrivateBin in the bin editor or comment
2. Click on the link once sent or in preview

### What happens
Browser opens a new tab with a BLOCKED error (ERR_BLOCKED_BY_RESPONSE). 

### What should happen
Browser opens up a new tab with your PrivateBin page

## Additional information
This error occurs on both chrome and firefox.

A workaround for now is to middle click your PrivateBin links, then it works as expected.

Also, the link that is generated after posting works just fine... 

## Basic information
**Server address**: https://pastebin.tcloud.dev

**Server OS:** Ubuntu 20.04.3 LTS in a docker container ([cloudron](https://cloudron.io))

**Webserver:** nginx/1.18.0

**Browser:** All

**PrivateBin version:** 1.6.0

I can reproduce this issue on <https://privatebin.net>: Yes

Here is an example: https://privatebin.net/?8c0a4fe6d179f5a0#DmaksTnxDTYRwx3j2XjbP6uq4hWQjirTG1ZQwS5KZmUY
_**Will expire on Aug 12, 2022**_

**Comment by rugk** [comment]
That feature is still crazy as I've read nowhere that this would be the effect of this header? Especially as it is same origin, is not it?

Would not opening tabs to the same origin in another tab maybe have the same effect (one can just edit the HTML locally in the browser to test, I just imagine).

I would like to see such a documentation or so, because we must somehow do sth special here or whatever I imagine.

**Comment by rugk** [comment]
Read more about that and https://xsleaks.dev/ is the class of vulnerabilities it should prevent/it prevents. This includes all kinds of cross-site information oracles. 
So our problem in this case could be https://xsleaks.dev/docs/attacks/window-references/. I.e. "noopener" that actually causes it to cause an oracle where you can guess sth.

So maybe if we remove that from same-origin i.e. the own domain that could make it work with that header?

**Comment by rugk** [comment]
https://xsleaks.dev/docs/defenses/opt-in/coop/ also explains the header and yeah it seems to be about the `window`(`.opener`) thing.

**Comment by elrido** [comment]
> So our problem in this case could be https://xsleaks.dev/docs/attacks/window-references/. I.e. "noopener" that actually causes it to cause an oracle where you can guess sth.

If I understand this page, all it lets the attacker detect is if the page could or couldn't be opened. It is explained that it is relevant to detect if a user is logged in or not, i.e. the behavior changes, depending on the session state of the user. In our case, all users are treated the same and will either always or never be able to open the link. Can you maybe give a more concrete example of an attack that removing the header will open our software to?

**Comment by rugk** [comment]
Well why this can be relevant is that it creates an oracle I.e. you can see the whole example general explanation here: https://xsleaks.dev/

Whether that's relevant in our case I have no idea. I guess api calls could be targeted the same way? Then other sites could cross-check with a crazy link whether an api call was successful on private in I.e. a paste exists?
I guess that's hardly relevant given we can also just open the link to do so.

Anyway I'd rather spend time on fixing this issue than thinking of potential threads attached to it. I mean its just that one very single case of self-opening a link to own domain that's broken.

**Comment by elrido** [comment]
I spent about 30 minutes digging through that page and it's scenarios and as far as I can tell, none of those scenario applies to our software, since we have no secret information on the API, no sessions, cookies and if the attacker can control the browser of the victim, they already have the key to decrypt the message. So, yes, let's fix the bug with #108 and remove this header that breaks our functionality and as far as we both can tell, doesn't gain us or our users any benefits.

**Comment by rugk** [comment]
BTW I could confirm in my browser that removing `target="_blank"` "fixes" the issue. 

Removing `noopener` did no difference. :|

**Comment by rugk** [comment]
The actual (potential) vulnerabilities affected by the header [are tagged here](https://xsleaks.dev/defenses/coop/):
* Window References  -> the "no API endpoints contain critical data" you said should apply here
* Frame Counting -> ~~we use no iframes and I don't see how that information would be valuable…~~ wait we use one: the PDF may be displayed as one (though that's a browser feature), so one _may_ be able to detect whether a paste contains a PDF or so? -> but our usual other [framing protection headers](https://xsleaks.dev/docs/defenses/opt-in/xfo/) seem to also prevent that.
* [Navigations](https://xsleaks.dev/docs/attacks/navigations/) -> again requires API endpoints or a download bar (also available via API - ahhh, now got it, that's clever though again unrelated for us)
* [Network Timing](https://xsleaks.dev/docs/attacks/timing-attacks/network-timing/) – uhm more complicated stuff, again seems to need API endpoints which convey a secret state
* [Execution Timing](https://xsleaks.dev/docs/attacks/timing-attacks/execution-timing/) -> this is potentially relevant for us given we have a _very_ long execution time (decryption time etc.) and one could interfere information from a timing attack here (starting with how large the encrypted paste is ending with decoding content or so). However, browsers do mitigations here (after all that's the crazy Spectre thing here) like multiprocesses. Also it's not clear whether COOP even helps to prevent at least the simple "Timing the Event Loop" (question mark in the table) and [guessing the encryption key with `#`](https://blog.sheddow.xyz/css-timing-attack/)  would be like breaking the encryption (your guessing a cryptographically random key, after all). Service Workers and other variants would supposedly be mitigated by COOP.
* [Hybrid Timing](https://xsleaks.dev/docs/attacks/timing-attacks/hybrid-timing/) -> it says COOP does not help here, iframe protections do.

TL;DR: "Execution Timing" (especially the "Busy Event Loop") is the only real risk I could see here and even that is a quite elaborate attack and browsers have mitigations for it, which I hope are… enough. Especially given that one would also somehow trigger another site visit at the same time than the victim opens the valid link (which decrypts), this makes it again less relevant in practice I guess. I could _imagine_ that it would be feasible to detect whether a paste correctly decrypted, which may not be the most sensitive information, however.

All very hypothetical etc. and all in all I'd say, yeah I am fine with removing it for now. We do not seem to gain a lot from COOP.
The alternative would be a JS workaround or so to remove `target="_blank"` from links to your own domain… :upside_down_face: 

PS: These modern attacks are getting really complicated. :see_no_evil:

**Comment by Nothing4You** [comment]
Why was this issue moved to this repo?
This applies to https://github.com/PrivateBin/PrivateBin as much as it applies here, as the header is also set on application level:

https://github.com/PrivateBin/PrivateBin/blob/628700afb14a908eb27bd9d5007869116db1f576/lib/Controller.php#L344

In addition to that, it's nearly impossible to find anything about this issue.

Searching any of the related errors in https://github.com/PrivateBin/PrivateBin does not yield any relevant results and this issue is unfortunately not indexed by Google either.
The only thing that showed up was some shitty GitHub content stealer website without any reference back to GitHub. 

It took me quite some time to finally find this issue, even after already finding the content stolen on that other website.

**Comment by rugk** [comment]
Oh thanks, you seem to be correct. Moving back...
