### ISSUE TITLE
bind() to 0.0.0.0:80 failed (13: Permission denied)

### ISSUE THREAD

**Issue by valumar** [PrivateBin/docker-nginx-fpm-alpine#11]
There were an error in logs:
[emerg] 215#215: bind() to 0.0.0.0:80 failed (13: Permission denied)

The container is broken. Please fix!

Container start cmd:
```
docker run -d --restart="always" --name privatebin --read-only -p 127.0.0.1:8080:80 -v privatebin-data:/srv/data privatebin/nginx-fpm-alpine:1.3.1
```

**Comment by elrido** [comment]
The container isn't "broken", of course, as it works fine for example at privatebin.net, but as the error states, you are hitting a permission issue.

In order for the nginx daemon in the image to be able to use a port below 1024 without running as the root user, we are setting the capabilities on that binary:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/0160b8e0515f36b030ec1d014485f5ea2e3e1936/Dockerfile#L56
I was wondering at the time if this feature is supported on all filesystem or docker/podman/kubernetes environments, but it worked on all the OS environments that I tested it on, which include xfs/ext4/btrfs, aufs and overlay2 (but not lvm thinpool), Ubuntu/CentOS/Alpine hosts, docker versions 1.13/17.03/19.03.

In your particular environment you seem to either not support capabilities on the filesystem you are using to back the /var/lib/docker directory or it has that privilege turned off to improve security on the filesystem or the global docker daemon configuration.

You can circumvent this either:
- by starting the container with the root user instead, by adding the parameter `-u 0` to your `docker run` statement - the services should still drop privileges and run under the configured `nobody` user id
- or by explicitly giving this container the required capability, by adding the parameter `--cap-add net_bind_service` to your `docker run` statement (this would give all binaries in that container that capability, not just nginx, but then you will only actually expose the containers port 80 and any other ports bound, would be ignored).

I haven't tested either of these (as all my docker environments let me use the capabilities set on the image, see above), so please let me know if one of these suggestions worked and which one you think is more secure and I will gladly add documentation for this error condition to the README.md.

**Comment by valumar** [comment]
Got an error in log with `-u 0` option:
```
[16-Nov-2019 08:30:34] ALERT: [pool www] user has not been defined
[16-Nov-2019 08:30:34] ALERT: [pool www] user has not been defined
[16-Nov-2019 08:30:34] ERROR: failed to post process the configuration
[16-Nov-2019 08:30:34] ERROR: failed to post process the configuration
[16-Nov-2019 08:30:34] ERROR: FPM initialization failed
[16-Nov-2019 08:30:34] ERROR: FPM initialization failed
```
For `--cap-add net_bind_service` option the same error as before:
```
2019/11/16 08:32:12 [emerg] 210#210: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)

```

```
# docker info
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 117
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.941GiB

Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by elrido** [comment]
Thank you for your quick feedback and the details of your installation.

So starting the container as root, php-fpm now fails, because the [ownership of the socket got removed](https://github.com/PrivateBin/docker-nginx-fpm-alpine/commit/a1d92a013ecc8aff86002cf4002f0f33af851735#diff-8b3ce2d1b92e93097409b6c73f17b9f2):
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/dba458cad96c2d0480289e4767f962c801605ec9/etc/php7/php-fpm.d/zz-docker.conf#L7-L8

Could you test if re-adding those two lines would solve your issue, by attaching the modified configuration into the container as a volume? If it does, I'll re-add them to the configuration file in the image, as they don't prevent it from running as a non-root user.

Reg. reason setcap is ignored on your setup: You may be facing an issue in [Debian's aufs-dkms package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863166). It seems to have still affected stretch, the version after jessie that your setup uses. As I imagine that neither upgrading to buster, nor re-compiling the package with the `CONFIG_AUFS_XATTR` enabled is an option for you, let's rather figure out how to get it to work in the system as it is.

Reg. diff between 1.2.1 vs 1.3.1: Back in 1.2.1 the applications got started as root user by supervisord, which allowed them to bind port 80 (hence the suggestion to override that) and then drop privileges. In 1.3.1 we are now using s6-overlay for service management instead and try to avoid using the root user to improve the security of the application. I agree the use of setcap is clunky, but it avoids having to change the port from 80 to something >1024 when upgrading the image to >=1.3.

**Comment by elrido** [comment]
Notes to self, idea for an alternative change: Have the nginx listen/proxy on both 80 and 8080, exposing both. Existing users can then upgrade the image and still use the port 80, users with the above FS limitations can opt to just use the 8080 one instead. Need to test if such a configuration would allow the nginx to start when it fails to bind port 80, by temporarily comment the setcap in the Dockerfile to emulate the issue.

If this works, docs could get updated to advertise 8080 as the port, but explaining that 80 is also available for backwards compatibility with the older releases of the image.
