### ISSUE TITLE
Your browser may require an HTTPS connection to support the WebCrypto API. Try switching to HTTPS.

### ISSUE THREAD

**Issue by nath2125** [PrivateBin/docker-nginx-fpm-alpine#130]
Hi there,

Using unraid to host this private bin.

Getting this error when i open the webui and dont know how to move past it.

Here are screenshots of the current setup, the image im using and error im getting in the webui
![9](https://user-images.githubusercontent.com/99367069/209756558-df3187ef-6cd7-4ea7-8e48-9d4d84127f45.PNG)
![8](https://user-images.githubusercontent.com/99367069/209756561-c7a5ae98-7af2-4dcb-9050-7fe6fc598dc7.PNG)
![7](https://user-images.githubusercontent.com/99367069/209756563-420d0688-fa66-4114-867e-3dda23716a2e.PNG)
![6](https://user-images.githubusercontent.com/99367069/209756565-9ce68899-5d14-4604-a0c0-c7b2803cd7d5.PNG)

**Comment by elrido** [comment]
As the error tries to explain, we use the browsers WebCrypto API for our encryption needs, which is not available when the browser considers the site not to be running in a secure context. Most often that happens when your website isn't offering https encryption, but there are also a [few other cases documented in the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-an-error-about-an-insecure-connection).

For [setting up HTTPS with unraid, check their manual](https://wiki.unraid.net/Manual/Security#Securing_webGui_connections_.28SSL.29).

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
