### ISSUE TITLE
Forbidden (403)

### ISSUE THREAD

**Issue by klapvogn** [PrivateBin/docker-nginx-fpm-alpine#200]
Hi,

First off I don't know if it's isolated to this image I use. But here goes

I run a Limnoria bot (python) that have a title reader plugin: but everytime I post a privateurl I get : `HTTPError: 403 Client Error: Forbidden for url:`

Any ideas

**Comment by rugk** [comment]
Yes, we try to block bots from accessing pastes if that is your concern, because obviously, they may invalidate burn-after-read onces, and the actual users cannot access them.

That said, technically, no 403 should be returned, but just a friendly bot message:
![grafik](https://github.com/user-attachments/assets/e7da5d45-dc27-45cf-9c2d-2286247b623d)

So maybe there is something else wrong with your setup, but you would need to provide more details etc.
