### ISSUE TITLE
Use multiple RUN commands instead of && concatenation

### ISSUE THREAD

**Issue by rugk** [PrivateBin/docker-nginx-fpm-alpine#21]
AFAIK Docker already checks the exist code and cancels the building process for creating an image when there is a non-zero exit code.

So there is no reason to use that huge long chain of `&&` concatenation in the Dockerfile, it just makes that less readable.

**Comment by elrido** [comment]
This is done to reduce the number of layers as per [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers). Every RUN creates a new layer and since we do install and uninstall some tools at the beginning and end, it is important to keep all these operations in a single RUN so the creation and deletion of files doesn't add to the size twice, when they really are only present temporarily and shouldn't be recorded at all.

The result is an image that's only 12 - 14 MiB in size, compressed.

An alternative to this approach, possible since 1.17, is the multi-stage build, which would let us work in any way we please in the first image and then copy only the needed parts over into a `FROM scratch` second stage.

**Comment by rugk** [comment]
Note:

> In older versions of Docker,

So yeah, maybe multi-stage-builds make sense.

But hmm, I see the reason and it seems mostly gpg2 which is uninstalled hmm…

**Comment by elrido** [comment]
And the downloaded signatures and archives in /tmp:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/246d479c05576e6f38b0b6351721d3ef34a0c5bb/Dockerfile#L57

Would not bump a PR that switches to a multi-stage build, but for now this IMO is mostly an aesthetic point and not a technical issue.
