### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by rugk** [PrivateBin/docker-nginx-fpm-alpine#31]
We have some unrelated build failures here for the Docker build…

https://github.com/PrivateBin/docker-nginx-fpm-alpine/runs/2269077284

**Comment by elrido** [comment]
There is nothing I could do other then try and restart the build. It seems docker buildx internally failed, hence the rpc error. Is Github maybe having some general issues on their build platform? All actions seemed to hang or fail since this afternoon...

**Comment by elrido** [comment]
I just noticed in my emails that there was a user creating and closing a PR in the main PB repo several times - that PR is gone, that user no longer exists (?!). Each PR will trigger a flurry of actions (you can still find these over in the main repos actions). Since we use a free account, our org is limited to a certain number of actions per day. I suspect we may simply have gotten rate limited. Unfortunately that means it will be some time until the multi-architecture 1.3.5 docker image gets published. :-(

**Comment by elrido** [comment]
Had to re-launch it one more time, but it just (finally) pushed all the images. Time to update the demo site! :relieved:
