### ISSUE TITLE
Chromium-based Edge seems not supported

### ISSUE THREAD

**Issue by xqm32** [PrivateBin/docker-nginx-fpm-alpine#39]
I used docker to run the image like this:

`docker run -d --restart="always" --read-only -p 8080:8080 -v $PWD/conf.php:/srv/cfg/conf.php:ro -v $PWD/privatebin-data:/srv/data privatebin/nginx-fpm-alpine`

I have disabled httpwarning in conf.php, but when I opened http://mydomain:8080 in New Edge(Chromium-based Edge), it showed an error that "PrivateBin requires a modern browser to work". And I opened http://mydomain:8080 with Safari in my iPad(iOS 14.6) . It worked without any error.

OS: Windows 10 19043.1023
Chromium-based Edge Version: 91.0.864.37
Language: ZH_CN

**Comment by elrido** [comment]
Please have a look at the FAQ link that you should see right below the error message - it should be this one: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-the-error-privatebin-requires-a-modern-browser-to-work

Very likely you see this because of this point in the FAQ entry:
> * and other browsers such as Chrome/Chromium-based ones disable the Web Crypto API when an insecure connection is used, i.e. e.g. when you access it over the net via HTTP instead of HTTPS. [...]

For comparison, you can point your browser to our [demo instance](https://privatebin.net/), it uses this container image as well. If it works but your instance not, it's likely because of the missing HTTPS.

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
