### ISSUE TITLE
Docker Conf.php doesn't get applied

### ISSUE THREAD

**Issue by SoulofSorrow** [PrivateBin/docker-nginx-fpm-alpine#60]
Hello, I have the same problem my docker container does not load the config. Unfortunately I do not understand why. I have checked the mount path, the env variable and the config file. Do I have to pay attention to anything with docker?

**Comment by rugk** [comment]
Could you please provide more information on your setup such as a docker-compose file or similar and the commands you execute to start the container?
Also please Provide the Docker version, OS etc.

Also what does "same problem" refer to? If there is alrafdy an open issue, please comment there or at least link it, if your issue is really not a duplicate…

**Comment by rugk** [comment]
Accidentally I found the issue you may be referring to. Is it https://github.com/PrivateBin/PrivateBin/issues/746? If so, does what is stated there help you? If not, why?

**Comment by SoulofSorrow** [comment]
Hey thanks I found it, now it works too. But I have already encountered the next problem. Is there an open source shortner for docker? Unfortunately yourls doesn't work and I couldn't get it to work with the instructions.

**Comment by rugk** [comment]
Yourls should work, please have a look at the FAQ and the links there: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#the-url-is-so-long-cant-i-just-use-an-url-shortener

If it does not, please open a new issue in the main repository (do check existing issues though!) and fill out gthe issue template there, please.

So as it seems the original question/bug has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by JCBird1012** [comment]
@SoulofSorrow what was your resolution for this? I’m encountering the same issue - I verified that file permissions are set correctly for /dev/cfg/conf.php, it’s mounted correctly in the container, and I’m at a loss as to what’s happening. 

PrivateBin/PrivateBin#746 doesn’t help me because the solution outlined there appears tailored to PrivateBin running outside of Docker. I don’t think I should be modifying Nginx configs inside the container itself (and those won’t persist anyways)

**Comment by elrido** [comment]
As a brief test if the file is accessible to the php-fpm process you can try to read it back via exec, it will run with the default unprivileged user ID:
```
docker exec <insert the running container ID or name here> cat srv/cfg/conf.php
```
Usually the permissions aren't correct, if the file gets ignored. You can similarly check those using an `ls -l` exec'ed inside the container. As per the README:

> Note that the volume mounted must be owned by UID 65534 / GID 82. If you run the container in a docker instance with "userns-remap" you need to add your subuid/subgid range to these numbers.

If you want to try adjusting the nginx configuration inside the container, to tweak the caching, see https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/README.md#adjusting-nginx-or-php-fpm-settings

**Comment by SoulofSorrow** [comment]
Hey I will test the uid and GUID setting. At the moment I am using version 1.3.5. version 1.3.5 works without any problems, only the latest update had caused problems. But I will test it tomorrow.
