### ISSUE TITLE
Enable PHP 8 JIT compiler?

### ISSUE THREAD

**Issue by rugk** [PrivateBin/docker-nginx-fpm-alpine#73]
I'm not sure about all technical details, but can't we enable PHP's cool new performance feature here? Or is it already enabled (by default)?

Ref https://github.com/shivammathur/setup-php#jit-configuration

**Comment by elrido** [comment]
According to https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.jit it is enabled by default for servers. Our unit tests, though, use xdebug which will disable this.

**Comment by rugk** [comment]
Ah okay, great, so we can close this issue? Or is anyone able to verify it is enabled? Maybe just with a simple `phpinfo()`?

**Comment by elrido** [comment]
I did so, using a phpinfo, before replying the above. We do have the opcache module loaded and consequently the JIT is enabled. See it's installation here:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L29

I can also report that on the VM that is running all of the privatebin things, including the demo website using this container, the monitored performance didn't change in a measurable way after I switched the instance from a 7.4 to an 8.0 image beginning of this year. The demo instance limits uploads to the default 10 MiB and the only CPU intense thing we do during paste creation is the compression test. Since that is probably just using zlib and isn't implemented in pure PHP, the JIT won't come into play in that area. I'd also count it as a low traffic instance, as it only has to handle about 43 k requests per day / 1825 requests per hour (those are average numbers from the demo containers nginx logs of last month, excluding the static info site and the directory).

Our server side code is comparably light-weight. No database connections (in case of the demo site) and we only transform from JSON to PHP arrays and back, no tricky XML mappings between different parts of the framework or custom template DSLs to parse at run-time or such. Hence our code should mostly get parsed and compiled once, when first loaded, then stored in the opcache in memory. The google cloud version of our application (in the next release) may benefit more from this, as it includes about 3.5 MiB of libraries of which we presumably only use a small subset.

The JIT matters for large code bases that exhaust the opcache's memory size and frequently encounter rarely used logic paths. This may be more the case with shared hosting of thousands of php apps on a single php service. Containers work around that issue, as each app instance gets it's own PHP stack and memory.
