### ISSUE TITLE
privatebin docker  behind nginx not in docker not loading on prt 80

### ISSUE THREAD

**Issue by D3an1el** [PrivateBin/docker-nginx-fpm-alpine#84]
Current setup:
I have nginx installed on separate server and private bin image on a docker on a different server. Unable to resolve on port 80 so i can lets encrypt. I changed from port 8080 to 8896 when i ran doceker image and changed paste location and custom conf.php file too.

1. Installed docker and image.
2. Able to view with localhost:8896 on local PC and ip:8896 on different pc on network

Tried:

```
upstream demo {
    server ipaddress:8896;
    keepalive 16;

server {
    server_name privatebin.net;

    listen  80;

    # proxy to demo site container
    location / {
        proxy_pass  http://demo;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "keep-alive";
     }
}
```
also

tried without upstream and 
```
Proxy_pass http://server-ip:8896;
```
Any help would be appreciated

**Comment by rugk** [comment]
So what is your actual issue? What error are you seeing? What do you expect to see? etc.

If you want top run/bind sth. on port 80 in default Linux systems you usually need to have root permissions, so ensure  ++the docker deamon has root access. Or~~ your nginx server, as that is the one you seem to use.  

Also that nginx config is just for a a reverse proxy? If so, okay, that should work.
Of course I hope `privatebin.net` is just a placeholder because obviously you cannot use our domain. :upside_down_face: 

There are plenty of tutorials [for setting up nginx as a reverse proxy](https://lmddgtfy.net/?q=nginx%20reverse%20proxy) and that task is hardly related to our project or this docker here, so have you tried following them already? If so, which ones? Which steps did you already take to solve the problem?

**Comment by D3an1el** [comment]
> So what is your actual issue? What error are you seeing? What do you expect to see? etc.
> 
> If you want top run/bind sth. on port 80 in default Linux systems you usually need to have root permissions, so ensure ++the docker deamon has root access. Or~~ your nginx server, as that is the one you seem to use.
> 
> Also that nginx config is just for a a reverse proxy? If so, okay, that should work. Of course I hope `privatebin.net` is just a placeholder because obviously you cannot use our domain. 🙃
> 
> There are plenty of tutorials [for setting up nginx as a reverse proxy](https://lmddgtfy.net/?q=nginx%20reverse%20proxy) and that task is hardly related to our project or this docker here, so have you tried following them already? If so, which ones? Which steps did you already take to solve the problem?

Yes the nginx is for proxy on a different server.There is no error appearing in  nginx error.log or access.log. i have added an A record in my dns server and it resolves to the page http://blahh.blahh.com:port. If i run dig command it shows the correct wan ip and dns server.I have other proxies running vaultwarden and etesync and they resolve and work. I have tried look around and unable to find a solution.  Maybe someone has got this setup and could shed some light.

FYI privatebin.net was example

**Comment by D3an1el** [comment]
Disregard fixed issue on my side

**Comment by rugk** [comment]
If there is anything that could help [other people finding this issue](https://xkcd.com/979/) about your issue, feel free to explain/post it here.
